spring.application.name=notedown

# DB properties - start
spring.datasource.url=jdbc:postgresql://localhost:5432/notedowndb
spring.datasource.username=postgres
spring.datasource.password=smpostgres
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# DB properties - end

jwt.secret=F3dDpoix24PK15IDkm4QrA9UHXGBZyEAPa4ce9yAtHc
