spring.application.name=notedown

# DB properties - start
spring.datasource.url=jdbc:postgresql://localhost:5432/notedowndb
spring.datasource.username=postgres
spring.datasource.password=smpostgres
spring.jpa.hibernate.ddl-auto=update

# DB properties - end

jwt.secret = W11eNf4d6BEjfxeLhT3s2hKkYs17PxlqTdDLlY1bdGI=