spring.application.name=notedown

# DB properties
spring.datasource.url=jdbc:postgresql://localhost:5432/notedowndb
spring.datasource.username=postgres
spring.datasource.password=smpostgres
spring.jpa.hibernate.ddl-auto=update
